---
- hosts: raspberrypi

  # All of the plays in this playbook are shell commands because the bundled version of python on Raspbian doesn't match the version of python that ansible needs.

  tasks:
    - name: Expand root filesystem.
      shell: >
        raspi-config --expand-rootfs
      args:
        executable: /bin/bash

    - name: reboot the pi.
      reboot:
        reboot_timeout: 600

    - name: Update DHCP servers.
      shell: >
        echo "static domain_name_servers=1.1.1.1 1.0.0.1" >> /etc/dhcpcd.conf && service dhcpcd restart && sleep 5
      args:
        executable: /bin/bash

    - name: Disable IPv6 networking (because it causes apt-get to fail).
      shell: >
        echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf && echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf && echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf && service networking restart && sleep 5
      args:
        executable: /bin/bash

    - name: Update package list (This could take 10+ minutes).
      shell: >
        apt-get update
      args:
        warn: false

    - name: Install tshark
      shell: >
        export DEBIAN_FRONTEND=noninteractive && apt-get install -qq -y tshark
      args:
        warn: false

    - name: Install tmux.
      shell: >
        apt-get install -qq -y tmux
      args:
        warn: false

    - name: Install mosh.
      shell: >
        apt-get install -qq -y mosh
      args:
        warn: false

    - name: Install nmap.
      shell: >
        apt-get install -qq -y nmap
      args:
        warn: false

    - name: Install iperf3.
      shell: >
        apt-get install -qq -y iperf3
      args:
        warn: false

    - name: Install htop.
      shell: >
        apt-get install -qq -y htop
      args:
        warn: false

    - name: Shut down pi.
      community.general.shutdown:
