---
- hosts: rancher
  gather_facts: no

  tasks:
    - name: wait for rancher OS to become available.
      wait_for_connection:
        delay: 60
    - name: Gather Facts
      setup:
    - name: Create a new project directory.
      ansible.builtin.file:
        path: /opt/owncloud
        state: directory
    - name: Copy docker compose to `/opt/owncloud`.
      ansible.builtin.copy:
        src: "{{playbook_dir}}/{{docker_compose | basename}}"
        dest: /opt/owncloud/docker-compose.yml
    - name: Copy `.env` file to `/opt/owncloud`.
      ansible.builtin.copy:
        src: "{{playbook_dir}}/{{env | basename}}"
        dest: /opt/owncloud/.env
    - name: Update owncloud admin password.
      ansible.builtin.lineinfile:
        path: /opt/owncloud/.env
        regexp: "^ADMIN_PASSWORD="
        line: "ADMIN_PASSWORD={{admin_password}}"
    - name: Update MariaDB root user password.
      ansible.builtin.lineinfile:
        path: /opt/owncloud/.env
        regexp: "^MARIADB_ROOT_PASSWORD="
        line: "MARIADB_ROOT_PASSWORD={{maria_db_root_password}}"
    - name: Update MariaDB owncloud user password.
      ansible.builtin.lineinfile:
        path: /opt/owncloud/.env
        regexp: "^MARIADB_PASSWORD="
        line: "MARIADB_PASSWORD={{maria_db_password}}"
    - name: Download docker compose.
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
        dest: /usr/local/bin/docker-compose
    - name: Make docker compose executable.
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: "0755"
    - name: link docker-compose binary.
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        owner: rancher
        group: rancher
        state: link
    - name: Check docker compose version.
      command: docker-compose --version
    - name: Start owncloud.
      command: docker-compose up -d
      args:
        chdir: /opt/owncloud
    - name: Wait for owncloud to become available.
      wait_for:
        port: 8080
        delay: 60
        timeout: 600
    - name: Delete .env file so passwords are not stored in plain text.
      ansible.builtin.file:
        path: /opt/owncloud/.env
        state: absent
